services:
  - type: web
    name: financiera-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"

  - type: web
    name: financiera-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
